version: '3.1'

services:

  db:
    image: postgres:11-alpine
    restart: always
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 0.0.0.0:5432:5432
